---
'VH': 0
'002': 0
'003': 0
'004': 0
'009': 0
'012': 0
'014': 0
'015': 0
'017': 0
'018': 0
'g2' : '-'
'g3' : '-'
'g4' : '-'
'g12' : '-'
'g14' : '-'
'g15' : '-'
'g17' : '-'
'g18' : '-'
'y2' : '-'
'y3' : '-'
'y4' : '-'
'y12' : '-'
'y14' : '-'
'y15' : '-'
'y17' : '-'
'y18' : '-'
