# __     ________ _      _      ______          __  _____     _______ _  __           
# \ \   / /  ____| |    | |    / __ \ \        / / |  __ \ /\|__   __| |/ /    /\     
#  \ \_/ /| |__  | |    | |   | |  | \ \  /\  / /  | |__) /  \  | |  | ' /    /  \    
#   \   / |  __| | |    | |   | |  | |\ \/  \/ /   |  ___/ /\ \ | |  |  <    / /\ \   
#    | |  | |____| |____| |___| |__| | \  /\  /    | |  / ____ \| |  | . \  / ____ \  
#    |_|  |______|______|______\____/   \/  \/     |_| /_/    \_\_|  |_|\_\/_/    \_\

deadlines:
 'VH' : '17.09.2014:20:00:00'
 '002' : '22.09.2014:20:00:00'
 '003' : '24.09.2014:20:00:00'
 '004' : '29.09.2014:20:00:00'
 '009' : '27.10.2014:20:00:00'
 '012' : '10.11.2014:20:00:00'
 '014' : '13.11.2014:06:00:00'
 '017' : '02.12.2014:06:00:00'

folders:
 'VH' : 'vhodno_nivo/'
 '002' : 'class002_homework/'
 '003' : 'class003_homework/'
 '004' : 'class004/'
 '009' : 'class009_homework/'
 '012' : 'class012_homework/'
 '014' : 'class014_homework/'
 '017' : 'class017_homework/'