require_relative 'task.rb'
class Task1 < Task
	def init_contexts
		context1_1 = {
			:file_name_format1=>"WRONG",
			:file_name_format2=>"CORRECT",
			:new_file_format1=>"JSON",
			:new_file_format2=>"CSV",
			:in_what_order=>"DESC",
			:expected=>
"[
  \"Wrong_Name_Name.rb\"
][
  \"Wrong_Name3.rb\"
][
  \"Wrong_Name2.rb\"
][
  \"Wrong_Name1.rb\"
][
  \"AWrong.rb\"
]",
			:expected1=>
"FirstName_LastName_5.rb
FirstName_LastName_2.rb
FirstName_LastName_1.rb
FirstName2_LastName2_2.rb
FirstName1_LastName1_19.rb
FirstName1_LastName1_1.rb",
			:example1=>
		"
		[
		  \"Wrong_Name4.rb\"
		][
		  \"Wrong_Name3.rb\"
		][
		  \"Wrong_Name2.rb\"
		][
		  \"Wrong_Name1.rb\"
		][
		  \"AWrong.rb\"
		]",
			:example2=>
			"
		FirstName3_LastName_5.rb
		FirstName2_LastName2_2.rb
		FirstName1_LastName1_19.rb
		FirstName1_LastName1_1.rb
		....
		FirstNameN_LastNameN_N.rb
		"
		}
		context1_2 = {
			:file_name_format1=>"CORRECT",
			:file_name_format2=>"WRONG",
			:new_file_format1=>"XML",
			:new_file_format2=>"HTML",
			:in_what_order=>"ASC",
			:expected=>
"<results>
<student>
<Name>FirstName1_LastName1_1.rb</Name>
</student>
<student>
<Name>FirstName1_LastName1_19.rb</Name>
</student>
<student>
<Name>FirstName2_LastName2_2.rb</Name>
</student>
<student>
<Name>FirstName_LastName_1.rb</Name>
</student>
<student>
<Name>FirstName_LastName_2.rb</Name>
</student>
<student>
<Name>FirstName_LastName_5.rb</Name>
</student>
</results>",
			:expected1=>
"<html>
<p>AWrong.rb</p>
<p>Wrong_Name1.rb</p>
<p>Wrong_Name2.rb</p>
<p>Wrong_Name3.rb</p>
<p>Wrong_Name_Name.rb</p>
</html>",
			:example1=>
			"
		<results>
			<student>
				<Name> FirstName1_LastName_19.rb </Name>
			</student>
			<student>
				<Name> FirstName2_LastName_2.rb </Name>
			</student>
			<student>
				<Name> FirstName3_LastName_1.rb </Name>
			</student>
			<student>
				<Name> FirstName4_LastName_2.rb </Name>
			</student>
			<student>
				<Name> FirstName5_LastName_5.rb </Name>
			</student>
		</results>
		",
			:example2=>
		"<html>
		<p>AWrong.rb</p>
		<p>Wrong_Name1.rb</p>
		<p>Wrong_Name2.rb</p>
		<p>Wrong_Name3.rb</p>
		<p>Wrong_Name_Name.rb</p>
		</html>"
		}
		context1_3 = {
			:file_name_format1=>"WRONG",
			:file_name_format2=>"CORRECT",
			:new_file_format1=>"CSV",
			:new_file_format2=>"HTML",
			:in_what_order=>"ASC",
			:expected=>
"AWrong.rb
Wrong_Name1.rb
Wrong_Name2.rb
Wrong_Name3.rb
Wrong_Name_Name.rb",
			:expected1=>
"FirstName1_LastName1_1.rb
FirstName1_LastName1_19.rb
FirstName2_LastName2_2.rb
FirstName_LastName_1.rb
FirstName_LastName_2.rb
FirstName_LastName_5.rb	",
			:example1=>
				"
		AWrong.rb
		Wrong_Name1.rb
		Wrong_Name2.rb
		Wrong_Name3.rb
		Wrong_Name_Name.rb
		",
			:example2=>
				"
		FirstName1_LastName1_1.rb
		FirstName2_LastName1_19.rb
		FirstName3_LastName2_2.rb
		FirstName4_LastName_1.rb
		...
		FirstNameN_LastName_N.rb
		"
}
		context1_4 = {
			:file_name_format1=>"WRONG",
			:file_name_format2=>"CORRECT",
			:new_file_format1=>"XML",
			:new_file_format2=>"JSON",
			:in_what_order=>"ASC",
			:expected=>
"<results>
<student>
<Name>AWrong.rb</Name>
</student>
<student>
<Name>Wrong_Name1.rb</Name>
</student>
<student>
<Name>Wrong_Name2.rb</Name>
</student>
<student>
<Name>Wrong_Name3.rb</Name>
</student>
<student>
<Name>Wrong_Name_Name.rb</Name>
</student>
</results>",
                        :expected1=>
"[
  \"FirstName1_LastName1_1.rb\"
][
  \"FirstName1_LastName1_19.rb\"
][
  \"FirstName2_LastName2_2.rb\"
][
  \"FirstName_LastName_1.rb\"
][
  \"FirstName_LastName_2.rb\"
][
  \"FirstName_LastName_5.rb\"
]",
				:example1=>
				"
		<results>
			<student>
				<Name> AWrong.rb </Name>
			</student>
			<student>
				<Name> Wrong_Name1.rb </Name>
			</student>
			<student>
				<Name> Wrong_Name2.rb </Name>
			</student>
			<student>
				<Name> Wrong_Name3.rb </Name>
			</student>
			<student>
				<Name> Wrong_Name_Name.rb </Name>
			</student>
		</results>
		",
                       		:example2=>
		"			
		[
		 \"FirstName1_LastName1_1.rb\"
		][
		  \"FirstName2_LastName1_19.rb\"
		][
		  \"FirstName3_LastName2_2.rb\"
		][
		  \"FirstName4_LastName_1.rb\"
		]"
		}
[context1_1,context1_2,context1_3,context1_4]
end
	def initialize
		super 'task1.eruby'
	end
end
