student_configuration:
 "VH" : "0"
 "002" : "0"
 "003" : "0"
 "004" : "0"
 "009" : "0"
 "012" : "0"
 "014" : "0"
 "015" : "0"
 "017x1" : "0"
 "017x2" : "0" 
 "g2" : "0"
 "g3" : "0"
 "g4" : "0"
 "g12" : "0"
 "g14" : "0"
 "g15" : "0"
 "g17x1" : "0"
 "g17x2" : "0"
 "y2" : "0"
 "y3" : "0"
 "y4" : "0"
 "y9" : "0"
 "y12" : "0"
 "y14" : "0"
 "y15" : "0"
 "y17x1" : "0"
 "y17x2" : "0"

teams&mmbs:
 Atanaska_Ivancheva : TeamInovation
 Borislav_Rusinov : ErrorBusters
 Borislav_Stratev : Project
 David_Georgiev : DandK
 Denis_Stoinev : CodePIMP$
 Dimitar_Andreev : Lazy_Slobs
 Dimitar_Matev : Programmable_Logics
 Dimitar_Nestorov : Happy_Satan
 Dimitar_Terziev : puts_team_name
 Elena_Karakoleva : ErrorKillers
 Emiliqn_Sokolov : PCMasterRace
 Georgi_Ivanov : Happy_satan
 Georgi_Velev : FastDelivery
 Gergan_Nikolov : 16-GB-RAM
 Hristiyan_Dodov : TeamOne
 Hristiyan_Velyakov : RubyDevelopers
 Hristo_Dachev : yellow_patka
 Iliyan_Germanov : CodePIMP$
 Iosyf_Saleh : Yu-Code-Oh!
 Ivailo_Ivanov : iM
 Ivelin_Slavchev : require'teamName'
 Ivo_Stratev : Project
 Ivo_Valchev : puts_team_name
 Kalin_Marinov : Programmable_Logics
 Kaloyan_Nikov : Yu-Code-Oh!
 Kamena_Dacheva : ErrorKillers
 Konstantin_Kostov : FastDelivery
 Konstantin_Vekilski : DandK
 Krassen_Angelov : require'teamName'
 Kristina_Pironkova : ErrorBusters
 Lili_Kokalova : LIST
 Lubomir_Yankov : require'teamName'
 Marian_Belchev : yellow_patka
 Martin_Grigorov : PCMasterRace
 Mladen_Karadimov : 16-GB-RAM
 Momchil_Angelov : Happy_satan
 Moretti_Georgiev : iM
 Nikola_Marinov : JustCrew
 Nikolay_Mihailov : FastDelivery
 Petko_Bozhinov : JustCrew
 Radoslav_Kostadinov : ErrorBusters
 Simeon_Shopkin : The_inventors
 Stanimir_Bogdanov : puts_team_name
 Stanislav_Iliev : PCMasterRace
 Stanislav_Valkanov : The_inventors
 Stefan_Iliev : CodePIMP$
 Stefan_Radev : LIST
 Tihomir_Lidanski : JustCrew
 Valentin_Georgiev : TeamInovation
 Valentin_Varbanov : 16-GB-RAM
 Vanya_Santeva : Yu-Code-Oh!
 Vasil_Kolev : Lazy_Slobs
 Velislav_Kostov : TeamOne
 Veselin_Dechev : RubyDevelopers
 Veselina_Kolova : TeamInovation
 Vladimir_Yordanov : TeamOne
