---
'1 You are given a folder with files.The Folder is passed as first argument;' : '@@/class016/Borislav_Stratev_2_B/fixtures/'
'1. You are given an argument for a path to CSV file:' : '@@/class016/Iliyan_Germanov_17_B/fixture/task1.csv'
'1. You are given an argument for folder with files in format FirstName_LastName_Digit.rb:' : '@@/class016/Iliyan_Germanov_17_B/fixture/'
'1. You are given two argument for two paths to two CSV files in format' : '@@/class016/Iliyan_Germanov_17_B/fixture/task3_1.csv @@/class016/Iliyan_Germanov_17_B/fixture/task3_2.csv'
'1. you are given a folder with files' : '@@/class016/Emiliqn_Sokolov_15_B/fixtures/'
'1. you have a folder with files' : '@@/class016/Emiliqn_Sokolov_15_B/fixtures/'
'1. You are given an argument for a folder with files that contains names;' : '@@/class016/Emiliqn_Sokolov_15_B/fixtures/'
'You are given an argument for a folder with .rb files.In' : '@@/class016/Hristiyan_Velyakov_28_A/fixture/'
'You are given an argument for a folder with .rb files. Other arguments should be discarded.' : '@@/class016/Hristiyan_Velyakov_28_A/fixture/'
'1. You are given an argument for a folder with files.' : '@@/class016/Ivelin_Slavchev_10_A/fixtures/'
'You are given an argument for a folder with .rb files.Find' : '@@/class016/Kaloyan_Nikov_19_B/fixture/'
'You are given an argument for a folder with files.Count' : '@@/class016/Kaloyan_Nikov_19_B/fixture/'
'1. You are given an argument for a folder with files.' : '@@/class016/Krassen_Angelov_14_A/fixtures/'
'You are given an argument for a folder with .rb files. Other arguments should be discarded.' : '@@/class016/Stanislav_Iliev_26_B/fixture/'
'You are given an argument for a folder with .rb files.In each' : '@@/class016/Stanislav_Iliev_26_B/fixture/'
'1. You are given one arguments which is a folders with files. Find the file named' : '@@/class016/Valentin_Varbanov_B_4/fixture/'
