
class XMLwriter
	def write(time_program, results)
		File.open("results_Lili_Kokalova_B_22.xml", "w") do |xml|
			xml.puts("<time> #{time_program} </time>")
			xml.puts("<results>")
			results.keys.sort.each do |k, v|
				xml.puts("	<student>") 
					xml.puts("		<FirstName> #{k.split("_")[0]} </FirstName>")
					xml.puts("		<LastName> #{k.split("_")[1]} </LastName>")
					xml.puts("		<VH>     #{results[k].values[0]} </VH>")
					xml.puts("		<002>    #{results[k].values[1]} </002>")
					xml.puts("		<003>    #{results[k].values[2]} </003>")
					xml.puts("		<004>    #{results[k].values[3]} </004>") 
					xml.puts("		<009>    #{results[k].values[4]} </009>")
					xml.puts("		<012>    #{results[k].values[5]} </012>")
					xml.puts("		<014>    #{results[k].values[6]} </014>")
					xml.puts("		<015>    #{results[k].values[7]} </015>")
					xml.puts("		<017h1>  #{results[k].values[8]} </017h1>")
					xml.puts("		<017h2>  #{results[k].values[9]} </017h2>")	
					xml.puts("		<018>  #{results[k].values[10]} </018>")
					xml.puts("		<g2>     #{results[k].values[11]} </g2>")
					xml.puts("		<g3>     #{results[k].values[12]} </g3>")
					xml.puts("		<g4>     #{results[k].values[13]} </g4>") 
					xml.puts("		<g12>    #{results[k].values[14]} </g12>")
					xml.puts("		<g14>    #{results[k].values[15]} </g14>")
					xml.puts("		<g15>    #{results[k].values[16]} </g15>")
					xml.puts("		<g017h1> #{results[k].values[17]} </g017h1>")
					xml.puts("		<g017h2> #{results[k].values[18]} </g017h2>")	
					xml.puts("		<g018> #{results[k].values[19]} </g018>")
					xml.puts("		<y2>     #{results[k].values[20]} </y2>")
					xml.puts("		<y3>     #{results[k].values[21]} </y3>")
					xml.puts("		<y4>     #{results[k].values[22]} </y4>") 
					xml.puts("		<y12>    #{results[k].values[23]} </y12>")
					xml.puts("		<y14>    #{results[k].values[24]} </y14>")
					xml.puts("		<y15>    #{results[k].values[25]} </y15>")
					xml.puts("		<y017h1> #{results[k].values[26]} </y017h1>")
					xml.puts("		<y017h2> #{results[k].values[27]} </y017h2>")
					xml.puts("		<y018> #{results[k].values[28]} </y018>")
				xml.puts("	</student>")
			end
			xml.puts("</results>")
		end
	end
end
