vhodno_nivo/**/*.*: "17, 9, 20"
class002_homework/**/*.rb: "22, 9, 20"
class003_homework/**/*.rb: "24, 9, 20"
class004/**/*.rb: "29, 9, 20"
class009_homework/**/*.pdf: "27, 10, 20"
class012_homework/**/*.rb: "10, 11, 20"
class014_homework/**/*.rb: "13, 11, 6"
class017_homework/homework1/*.rb: "02, 12, 6"
