"VH":
    "folder" : 'Dir.glob("#{ARGV[0]}/vhodno_nivo/**/*.*")'
    "deadline" : "17.09.2014:20:00:00"
"002":
    "folder" : 'Dir.glob("#{ARGV[0]}/class002_homework/**/*.rb")'
    "deadline" : "22.09.2014:20:00:00"

"003":
    "folder" : "Dir.glob("#{ARGV[0]}/class003_homework/**/*.rb")"
    "deadline" : "24.09.2014:20:00:00"

"004":
    "folder" : "Dir.glob("#{ARGV[0]}/class004/**/*.rb")"
    "deadline" : "29.09.2014:20:00:00"

"009":
    "folder" : "Dir.glob("#{ARGV[0]}/class009_homework/**/*.pdf")"
    "deadline" : "27.10.2014:20:00:00"
"012":
    "folder" : "Dir.glob("#{ARGV[0]}/class012_homework/**/*_*_*_*.rb")"
    "deadline" : "10.11.2014:20:00:00"

"014":
    "folder" : "Dir.glob("#{ARGV[0]}/class014_homework/**/*_*_*_*.rb")"
    "deadline" : "13.11.2014:06:00:00"

"015":
    "folder" : "Dir.glob("#{ARGV[0]}/class015_homework/**/*_*_*_*.rb")"
    "deadline" : "20.11.2014:06:00:00"
"017x1":
    "folder" : "Dir.glob("#{ARGV[0]}/class017_homework/homework1/**/*_*_*_*.rb")"
    "deadline" : "02.12.2014:06:00:00"
"017x2":
    "folder" : "Dir.glob("#{ARGV[0]}/class017_homework/homework2/**/*_*_*_*.rb")"
    "deadline" : "02.12.2014:06:00:00"

